on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build v8
        run: bash build.sh
      - name: Show files
        run: cd v8;find|grep d8
      - name: Release to GitHub
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: d8
          automatic_release_tag: d8
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            v8/out/ia32.release/*
